/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppShell: typeof import('./src/components/AppShell.vue')['default']
    BottomNav: typeof import('./src/components/BottomNav.vue')['default']
    ConfirmDialog: typeof import('./src/components/ConfirmDialog.vue')['default']
    IdScanDialog: typeof import('./src/components/IdScanDialog.vue')['default']
    KeyCardDialog: typeof import('./src/components/KeyCardDialog.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    ResponsiveList: typeof import('./src/components/ResponsiveList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatTile: typeof import('./src/components/StatTile.vue')['default']
    ThemeSwitch: typeof import('./src/components/ThemeSwitch.vue')['default']
  }
}
